In [31]:
import pandas as pd

df  = pd.read_csv(r"C:/Users/ISMAIL/OneDrive/Documents/data science projects/cleanedandanalyzed_dataset.csv")

In [32]:
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Age Group,Has Dependents,Total Charges Per Month
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,0.064217,-0.744447,-0.248295,-0.273281,-0.434164,974.81,Stayed,35-44,0,1040.41
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,-2.166213,-0.766907,4.601998,0.125046,-0.771135,610.28,Stayed,45-54,0,606.28
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,0.330202,-0.882320,-0.248295,-0.273281,-0.725792,415.45,Churned,45-54,0,489.35
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,1.102521,-0.460031,-0.248295,-0.273281,-0.457609,1599.51,Churned,65+,0,1697.51
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,0.650666,-0.888255,-0.248295,-0.273281,-0.858620,289.54,Churned,65+,0,373.44

In [33]:
#Data type conversion
#Convert "Gender," "Married," "City," "Offer," and other categorical columns from object to the appropriate data type (e.g., category or boolean).
#Convert "Avg Monthly GB Download" from object to a numeric data type (e.g., float) for easier analysis.

df['Gender'] = df['Gender'].astype('category')
df['Married'] = df['Married'].astype('category')
df['City'] = df['City'].astype('category')
df['Offer'] = df['Offer'].astype('category')
df['Avg Monthly GB Download'] = pd.to_numeric(df['Avg Monthly GB Download'], errors='coerce') 
df['Gender'] = df['Gender'].astype('category')
df['Married'] = df['Married'].astype('category')
df['City'] = df['City'].astype('category')
df['Offer'] = df['Offer'].astype('category')
df['Avg Monthly GB Download'] = pd.to_numeric(df['Avg Monthly GB Download'], errors='coerce')

KeyError: 'Avg Monthly GB Download'

In [34]:
df.dtypes

Customer ID                      object
Gender                         category
Age                               int64
Married                        category
Number of Dependents              int64
City                           category
Zip Code                          int64
Latitude                        float64
Longitude                       float64
Number of Referrals               int64
Tenure in Months                  int64
Offer                          category
Phone Service                    object
Internet Service                 object
Internet Type                    object
Online Security                  object
Online Backup                    object
Device Protection Plan           object
Premium Tech Support             object
Streaming TV                     object
Streaming Movies                 object
Streaming Music                  object
Unlimited Data                   object
Contract                         object
Paperless Billing                object
Payment Method                   object
Monthly Charge                  float64
Total Charges                   float64
Total Refunds                   float64
Total Extra Data Charges        float64
Total Long Distance Charges     float64
Total Revenue                   float64
Customer Status                  object
Age Group                        object
Has Dependents                    int64
Total Charges Per Month         float64
dtype: object

In [35]:
# Creating a new column for age group based on the 'Age' column
df['Age Group'] = pd.cut(df['Age'], bins=[0, 17, 24, 34, 44, 54, 64, 200], labels=['0-17', '18-24', '25-34', '35-44', '45-54', '55-64', '65+'])

# Creating a binary variable indicating whether a customer has dependents
df['Has Dependents'] = df['Number of Dependents'].apply(lambda x: 1 if x > 0 else 0)

# Calculating the total charges per month
df['Total Charges Per Month'] = df['Monthly Charge'] + df['Total Charges'] - df['Total Refunds'] + df['Total Extra Data Charges'] + df['Total Long Distance Charges']

# Display the updated DataFrame
print(df)

     Customer ID  Gender  Age Married  Number of Dependents          City  \
0     0002-ORFBO  Female   37     Yes                     0  Frazier Park
1     0003-MKNFE    Male   46      No                     0      Glendale
2     0004-TLHLJ    Male   50      No                     0    Costa Mesa
3     0011-IGKFF    Male   78     Yes                     0      Martinez
4     0013-EXCHZ  Female   75     Yes                     0     Camarillo
...          ...     ...  ...     ...                   ...           ...
7038  9987-LUTYD  Female   20      No                     0       La Mesa
7039  9992-RRAMN    Male   40     Yes                     0     Riverbank
7040  9992-UJOEL    Male   22      No                     0           Elk
7041  9993-LHIEB    Male   21     Yes                     0  Solana Beach
7042  9995-HOTOH    Male   36     Yes                     0   Sierra City

      Zip Code   Latitude   Longitude  Number of Referrals  ...  \
0        93225  34.827662 -118.999073                    2  ...
1        91206  34.162515 -118.203869                    0  ...
2        92627  33.645672 -117.922613                    0  ...
3        94553  38.014457 -122.115432                    1  ...
4        93010  34.227846 -119.079903                    3  ...
...        ...        ...         ...                  ...  ...
7038     91941  32.759327 -116.997260                    0  ...
7039     95367  37.734971 -120.954271                    1  ...
7040     95432  39.108252 -123.645121                    0  ...
7041     92075  33.001813 -117.263628                    5  ...
7042     96125  39.600599 -120.636358                    1  ...

      Monthly Charge Total Charges Total Refunds Total Extra Data Charges  \
0           0.064217     -0.744447     -0.248295                -0.273281
1          -2.166213     -0.766907      4.601998                 0.125046
2           0.330202     -0.882320     -0.248295                -0.273281
3           1.102521     -0.460031     -0.248295                -0.273281
4           0.650666     -0.888255     -0.248295                -0.273281
...              ...           ...           ...                      ...
7038       -0.270668     -0.678434     -0.248295                -0.273281
7039        0.689122     -0.179454     -0.248295                -0.273281
7040       -0.426093     -0.965321     -0.248295                -0.273281
7041        0.136321      1.035764     -0.248295                -0.273281
7042       -0.147289      0.629779     -0.248295                -0.273281

     Total Long Distance Charges Total Revenue Customer Status Age Group  \
0                      -0.434164        974.81          Stayed     35-44
1                      -0.771135        610.28          Stayed     45-54
2                      -0.725792        415.45         Churned     45-54
3                      -0.457609       1599.51         Churned       65+
4                      -0.858620        289.54         Churned       65+
...                          ...           ...             ...       ...
7038                   -0.168024       1349.74          Stayed     18-24
7039                   -0.463822       2230.10         Churned     35-44
7040                   -0.840785        129.99          Joined     18-24
7041                   -0.717005       4769.69          Stayed     18-24
7042                   -0.884770       3707.60          Stayed     35-44

     Has Dependents Total Charges Per Month
0                 0               -1.139380
1                 0               -8.181208
2                 0               -1.302896
3                 0                0.159895
4                 0               -1.121194
...             ...                     ...
7038              0               -1.142112
7039              0                0.020861
7040              0               -2.257186
7041              0                0.430095
7042              0               -0.427266

[7043 rows x 36 columns]

In [36]:
# Select the numerical columns for standardization
numeric_columns = ['Monthly Charge', 'Total Charges', 'Total Refunds', 'Total Extra Data Charges', 'Total Long Distance Charges']

# Perform z-score normalization on the selected columns
df[numeric_columns] = (df[numeric_columns] - df[numeric_columns].mean()) / df[numeric_columns].std()

In [37]:
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Age Group,Has Dependents,Total Charges Per Month
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,0.064217,-0.744447,-0.248295,-0.273281,-0.434164,974.81,Stayed,35-44,0,-1.139380
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,-2.166213,-0.766907,4.601998,0.125046,-0.771135,610.28,Stayed,45-54,0,-8.181208
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,0.330202,-0.882320,-0.248295,-0.273281,-0.725792,415.45,Churned,45-54,0,-1.302896
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,1.102521,-0.460031,-0.248295,-0.273281,-0.457609,1599.51,Churned,65+,0,0.159895
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,0.650666,-0.888255,-0.248295,-0.273281,-0.858620,289.54,Churned,65+,0,-1.121194

In [38]:
df.dtypes

Customer ID                      object
Gender                         category
Age                               int64
Married                        category
Number of Dependents              int64
City                           category
Zip Code                          int64
Latitude                        float64
Longitude                       float64
Number of Referrals               int64
Tenure in Months                  int64
Offer                          category
Phone Service                    object
Internet Service                 object
Internet Type                    object
Online Security                  object
Online Backup                    object
Device Protection Plan           object
Premium Tech Support             object
Streaming TV                     object
Streaming Movies                 object
Streaming Music                  object
Unlimited Data                   object
Contract                         object
Paperless Billing                object
Payment Method                   object
Monthly Charge                  float64
Total Charges                   float64
Total Refunds                   float64
Total Extra Data Charges        float64
Total Long Distance Charges     float64
Total Revenue                   float64
Customer Status                  object
Age Group                      category
Has Dependents                    int64
Total Charges Per Month         float64
dtype: object

In [39]:
df.to_csv('C:/Users/ISMAIL/OneDrive/Documents/data science projects/cleanedandanalyzed_dataset.csv', index=False)

PermissionError: [Errno 13] Permission denied: 'C:/Users/ISMAIL/OneDrive/Documents/data science projects/cleanedandanalyzed_dataset.csv'